### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInplbmdsaW5zaGVuZ0BpbW9vYy5jb21cIn0iLCJqdGkiOiJkZWY0ZmQyNy05OGEzLTQwOTItOGJmYy02ZjZjMTQ0ZjkwZjQiLCJleHAiOjE3MTM5NzQ0MDB9.wwbPl-AihrsOcJa1lY7rR8O4aXg4LVI_xUgepTDyrAra7Zb34b0gQQO5jNh6gowPq6PDgPafFARctf-zTuO-OWJtIrPQTLcv613_l2-W1QlR9_kHk1fam9PFCZk9Deox9nCHNLBLSMuqoBd_BkugN_UfWHzobWLuIcxA9KhfnjAGVqhYvTOX2WaadToIO4huwa3T0WJJB8AZRSjXd6eru_EN-iVM8P41owt3wCD65yOUSrAT8SbveMgWcIr40N-qJVpKlqeFC3UiPwegkV6ymnsjUTDaBUQFWbGXw24IhncM-S3S0nPu7YhISOY9K-WfU-up0ZXEOHbphMuzEh-bHg
token: imooc
