### 导入商品
POST http://127.0.0.1:9001/imooc/ecommerce-goods-service/async-goods/import-goods
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInplbmdsaW5zaGVuZ0BpbW9vYy5jb21cIn0iLCJqdGkiOiJkMjYxMzczZS0yZTNmLTQ5NjUtODkyMS1kN2YzYTdjZTI0YjMiLCJleHAiOjE3MTM5NzQ0MDB9.QW26jm_lwavxnb9DqeovJ3woLuaJjfaHpNMmySjdB_MblNJ-vfTJKu8DpbgTkIKsL8_2c3hJX-pDSgM1mR6xqtZpAxN_phvMhINPBmsKOvYNAcog61IltAf4nB2JCmjNRG-iUWWZPS53f5Bqfa5lv6RdSv_XtaHLyBJK4HOZAM7oOFHaupJjFg3Zq2Vwi2nDnk4wFcTi2YNBhVtGswdNwZWp8v04XT4cW3uOpOkAgzvi0Z2nEvv6oOi-FA59jK_5wz5jNeYmj0QIdopSvWcArbAb0r_dNmWl4j8jZsbKfQpdxKgWA2LVq5i2NLhdJEVbuxzKxsFQLX6FWTPhnpqXmQ

[
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 11",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 100000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  },
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 12",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 150000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  },
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 13",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 160000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  }
]


### 查询导入商品状态
GET http://127.0.0.1:9001/imooc/ecommerce-goods-service/async-goods/task-info?taskId=ca975c32-0a1c-4612-8dc9-3d6412d9f40a
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInplbmdsaW5zaGVuZ0BpbW9vYy5jb21cIn0iLCJqdGkiOiJkMjYxMzczZS0yZTNmLTQ5NjUtODkyMS1kN2YzYTdjZTI0YjMiLCJleHAiOjE3MTM5NzQ0MDB9.QW26jm_lwavxnb9DqeovJ3woLuaJjfaHpNMmySjdB_MblNJ-vfTJKu8DpbgTkIKsL8_2c3hJX-pDSgM1mR6xqtZpAxN_phvMhINPBmsKOvYNAcog61IltAf4nB2JCmjNRG-iUWWZPS53f5Bqfa5lv6RdSv_XtaHLyBJK4HOZAM7oOFHaupJjFg3Zq2Vwi2nDnk4wFcTi2YNBhVtGswdNwZWp8v04XT4cW3uOpOkAgzvi0Z2nEvv6oOi-FA59jK_5wz5jNeYmj0QIdopSvWcArbAb0r_dNmWl4j8jZsbKfQpdxKgWA2LVq5i2NLhdJEVbuxzKxsFQLX6FWTPhnpqXmQ
